name: Scrape & Publish

on:
  schedule:
    - cron: "0 22 * * FRI"
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
      - name: Run scraper
        env:
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
        run: python scraper/scraper.py
      - name: Commit & push if changed
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --quiet || (git commit -m "data: update $(date -u +'%Y-%m-%d %H:%M:%S')" && git push)
